# fly.toml app configuration file generated for memo-nft-api on 2025-03-24T16:21:48+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memo-nft-api-prod'
primary_region = 'sin'

[build]

[env]
  PONDER_RPC_URL_8453 = "https://base.g.alchemy.com/v2/sYXl7-YsC4ki_MbJToI2XJ7DgxjQ8f7R"
  PONDER_RPC_URL_84532 = "https://base-sepolia.g.alchemy.com/v2/sYXl7-YsC4ki_MbJToI2XJ7DgxjQ8f7R"
  MEMO_NFT_ADDRESS = "0xb1e052156676750d193d800d7d91ea0c7ceeadf0"
  START_BLOCK = "23233931"
  APP_ENV = "PROD"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


[checks]
  [checks.healthz]
    port = 3000
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/healthz'