# fly.toml app configuration file generated for memo-nft-api-prod on 2025-03-26T14:39:42+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'memo-nft-api-prod'
primary_region = 'sin'

[build]

[env]
  APP_ENV = 'PROD'
  MEMO_NFT_ADDRESS = '0x07f3ed54e0b2D07cC522c4FC12EbA80E6D3A8DeB'
  PONDER_RPC_URL_8453 = 'https://base.g.alchemy.com/v2/sYXl7-YsC4ki_MbJToI2XJ7DgxjQ8f7R'
  PONDER_RPC_URL_84532 = 'https://base-sepolia.g.alchemy.com/v2/sYXl7-YsC4ki_MbJToI2XJ7DgxjQ8f7R'
  START_BLOCK = '28092387'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.healthz]
    port = 3000
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/healthz'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
