name: Deploy to Fly.io

on:
  push:
    branches:
      - develop
    tags:
      - 'v*.*.*'

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    name: Deploy to Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Dev
        run: |
          flyctl deploy --config fly-dev.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Production
        run: |
          flyctl deploy --config fly-prod.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
