name: Deploy to Development

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to Dev
        run: |
          flyctl deploy --config fly-dev.toml --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
